# Generated by Django 5.0 on 2024-01-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_guests', models.IntegerField()),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
    ]
